version: '3'
services:

  recommend_api:
    tty: true
    image: recommend_image
    container_name: recommend_api
    command: bash -c "python3 app.py"
    volumes:
      - ${PWD}/models:/recommend/models
    network_mode: host
  
  retrain_module:
    tty: true
    image: recommend_image
    container_name: retrain_module
    command: bash -c "python3 main.py"
    volumes:
      - ${PWD}/models:/recommend/models
    network_mode: host
  

